In [1]:
import tensorflow as tf

In [2]:
# data location (*.csv)
data_dir = '../data'
data_file_names = ['data1.csv', 'data2.csv']
data_files = ['{}/{}'.format(data_dir, f) for f in data_file_names]

In [4]:
# file name queue
filename_queue = tf.train.string_input_producer(data_files)

In [5]:
# reader
reader = tf.TextLineReader(skip_header_lines=1)
key, value = reader.read(filename_queue)

In [6]:
# decoder
record_defaults = [[0.0], [0.0], [0.0]]
col1, col2, col3 = tf.decode_csv(value, record_defaults=record_defaults)
features = tf.stack([col1, col2, col3])

In [10]:
with tf.Session() as sess:
    
    # coordinator
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)
    
    try:        
        for i in range(20):
            data1 = sess.run(features)
            data2 = sess.run(features)
            print('---')
            print(data1)
            print(data2)

    except tf.errors.OutOfRangeError:        
        print('Done training -- epoch limit reached')
        
    finally:
        coord.request_stop()
        
    coord.join(threads)
        

---
[ 100.  101.  102.]
[ 200.  201.  202.]
---
[ 1.  2.  3.]
[ 10.  11.  12.]
---
[ 21.  22.  23.]
[ 1.  2.  3.]
---
[ 10.  11.  12.]
[ 21.  22.  23.]
---
[ 100.  101.  102.]
[ 200.  201.  202.]
---
[ 100.  101.  102.]
[ 200.  201.  202.]
---
[ 1.  2.  3.]
[ 10.  11.  12.]
---
[ 21.  22.  23.]
[ 100.  101.  102.]
---
[ 200.  201.  202.]
[ 1.  2.  3.]
---
[ 10.  11.  12.]
[ 21.  22.  23.]
---
[ 100.  101.  102.]
[ 200.  201.  202.]
---
[ 1.  2.  3.]
[ 10.  11.  12.]
---
[ 21.  22.  23.]
[ 100.  101.  102.]
---
[ 200.  201.  202.]
[ 1.  2.  3.]
---
[ 10.  11.  12.]
[ 21.  22.  23.]
---
[ 100.  101.  102.]
[ 200.  201.  202.]
---
[ 1.  2.  3.]
[ 10.  11.  12.]
---
[ 21.  22.  23.]
[ 100.  101.  102.]
---
[ 200.  201.  202.]
[ 1.  2.  3.]
---
[ 10.  11.  12.]
[ 21.  22.  23.]
