In [1]:
import tensorflow as tf
import tflearn

hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
Scipy not supported!


In [26]:
# Logical NOT operator
X = [[0.], [1.]]
Y = [[1.], [0.]]

# Graph definition
with tf.Graph().as_default() as sess:
    g = tflearn.input_data(shape=[None, 1])
    g = tflearn.fully_connected(g, 128, activation='linear')
    g = tflearn.fully_connected(g, 128, activation='linear')
    g = tflearn.fully_connected(g, 1, activation='sigmoid')
    g = tflearn.regression(g, optimizer='sgd', learning_rate=2.,
                           loss='mean_square')

    # Model training
    m = tflearn.DNN(g)
    m.fit(X, Y, n_epoch=100, snapshot_epoch=False)

    # Test model
    print("Testing NOT operator")
    print("NOT 0:", m.predict([[0.]]))
    print("NOT 1:", m.predict([[1.]]))
    


Training Step: 100  | total loss: 0.01877 | time: 0.001s
| SGD | epoch: 100 | loss: 0.01877 -- iter: 2/2
Testing NOT operator
('NOT 0:', [[0.9743992686271667]])
('NOT 1:', [[0.02071264758706093]])


In [38]:
matrix2 = tf.constant([[2.],[2.]])
matrix2.shape

TensorShape([Dimension(2), Dimension(1)])

In [39]:
matrix1 = tf.constant([[3., 3.]])

# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])

In [43]:
sess = tf.InteractiveSession()

In [46]:
sess.run(tf.transpose(matrix1))

array([[ 3.],
       [ 3.]], dtype=float32)

In [58]:
m1 = tf.random_uniform([5, 5], 0, 5)
m2 = tf.random_normal([5,5], 0, 1)
#m2i = tf.matrix_inverse(m2)
mp = tf.matmul(m1, m2)

sess.run(mp)

array([[  2.22424126,   8.68441677,   8.55447865,  -5.29284   ,
          6.37790298],
       [  1.21231508,   3.24558783,   7.7033062 ,   2.43693614,
         -4.28062201],
       [  2.0210402 ,   4.12528419,   1.16874492,   6.95659018,
          2.27318072],
       [  2.48607898,   9.63694286,  11.50549603,  -5.68012381,
          3.77124047],
       [  1.09980285,   3.89597631,   0.70032859,  -2.32807684,
          2.27876663]], dtype=float32)

In [94]:
m1 = tf.random_uniform([1000000, 5], 0, 5)
v1 = tf.random_uniform([5, 1], 0, 5)
prod = tf.matmul(m1, v1)
sess.run(prod)


array([[ 41.49773788],
       [ 15.93252468],
       [ 31.01698875],
       ..., 
       [ 15.82594204],
       [ 36.40784836],
       [ 26.88687897]], dtype=float32)

In [88]:
m1.shape

TensorShape([Dimension(1000000), Dimension(5)])